main: tld.example.myplugin.Main
name: MyPlugin
version: 1.0
author: me
description: An Example plugin
commands:
  mycommand:
    description: An example command
    usage: /mycommand
    permission: myplugin.mycommand
    permission-message: You don't have the myplugin.mycommand permission.